export const categoryOptions: string[] = [
  'Butler Services',
  'House Cleaning',
  'Chauffeur & Drivers',
  'Bartending',
  'Personal Training',
  'Childcare & Nanny',
  'Tutoring',
  'Event Planning',
  'Landscaping & Gardening',
  'Pet Care',
  'Elderly Care',
  'Music Lessons',
  'Home Maintenance',
  'Personal Styling',
  'Yoga & Fitness',
  'Pool Maintenance',
  'Interior Design',
  'IT Support',
  'Photography',
  'Translation Services',
];
