import { User } from '../../models/user-card.model';

export const users: User[] = [
  {
    id: '1',
    firstName: 'Karim',
    lastName: 'Hassan',
    profileImage: 'https://ui-avatars.com/api/?name=Karim+Hassan&background=0D8ABC&color=fff',
    title: 'Certified Private Butler',
    category: 'Butler Services',
    rating: 4.9,
    reviewCount: 120,
    skills: ['EVENT MANAGEMENT', 'FRENCH SPEAKING'],
    hourlyRate: 25,
    verified: true,
    availableToday: true,
  },
  {
    id: '1',
    firstName: 'Karim',
    lastName: 'Hassan',
    profileImage: 'https://ui-avatars.com/api/?name=Karim+Hassan&background=0D8ABC&color=fff',
    title: 'Certified Private Butler',
    category: 'Butler Services',
    rating: 4.9,
    reviewCount: 120,
    skills: ['EVENT MANAGEMENT', 'FRENCH SPEAKING'],
    hourlyRate: 25,
    verified: true,
    availableToday: true,
  },
  {
    id: '2',
    firstName: 'Sarah',
    lastName: 'Johnson',
    profileImage: 'https://ui-avatars.com/api/?name=Sarah+Johnson&background=random',
    title: 'Professional Chef',
    category: 'Butler Services',
    rating: 4.8,
    reviewCount: 95,
    skills: ['FINE DINING', 'ITALIAN CUISINE'],
    hourlyRate: 35,
    verified: true,
    availableToday: false,
  },
  {
    id: '3',
    firstName: 'Maria',
    lastName: 'Rodriguez',
    profileImage: 'https://ui-avatars.com/api/?name=Maria+Rodriguez&background=random',
    title: 'Senior Housekeeper',
    category: 'House Cleaning',
    rating: 4.7,
    reviewCount: 210,
    skills: ['DEEP CLEANING', 'ORGANIZATION'],
    hourlyRate: 20,
    verified: true,
    availableToday: true,
  },
  {
    id: '4',
    firstName: 'James',
    lastName: 'Wilson',
    profileImage: 'https://ui-avatars.com/api/?name=James+Wilson&background=random',
    title: 'Executive Chauffeur',
    category: 'Chauffeur & Drivers',
    rating: 5.0,
    reviewCount: 45,
    skills: ['DEFENSIVE DRIVING', 'SECURITY'],
    hourlyRate: 30,
    verified: true,
    availableToday: true,
  },
  {
    id: '5',
    firstName: 'Yuki',
    lastName: 'Tanaka',
    profileImage: 'https://ui-avatars.com/api/?name=Yuki+Tanaka&background=random',
    title: 'Math Tutor',
    category: 'Tutoring',
    rating: 4.9,
    reviewCount: 88,
    skills: ['CALCULUS', 'PHYSICS'],
    hourlyRate: 40,
    verified: true,
    availableToday: false,
  },
  {
    id: '6',
    firstName: 'Emily',
    lastName: 'Parker',
    profileImage: 'https://ui-avatars.com/api/?name=Emily+Parker&background=random',
    title: 'Nanny & Childcare',
    category: 'Childcare & Nanny',
    rating: 4.6,
    reviewCount: 15,
    skills: ['CPR CERTIFIED', 'EARLY EDUCATION'],
    hourlyRate: 22,
    verified: false,
    availableToday: true,
  },
  {
    id: '7',
    firstName: 'Ahmed',
    lastName: 'Al-Fayed',
    profileImage: 'https://ui-avatars.com/api/?name=Ahmed+Al-Fayed&background=random',
    title: 'Personal Trainer',
    category: 'Personal Training',
    rating: 4.8,
    reviewCount: 102,
    skills: ['WEIGHT LOSS', 'NUTRITION'],
    hourlyRate: 50,
    verified: true,
    availableToday: true,
  },
  {
    id: '8',
    firstName: 'Isabella',
    lastName: 'Rossi',
    profileImage: 'https://ui-avatars.com/api/?name=Isabella+Rossi&background=random',
    title: 'Event Planner',
    category: 'Event Planning',
    rating: 4.5,
    reviewCount: 30,
    skills: ['WEDDINGS', 'CATERING LOGISTICS'],
    hourlyRate: 45,
    verified: true,
    availableToday: false,
  },
  {
    id: '9',
    firstName: 'David',
    lastName: 'Kim',
    profileImage: 'https://ui-avatars.com/api/?name=David+Kim&background=random',
    title: 'Landscape Gardener',
    category: 'Landscaping & Gardening',
    rating: 4.7,
    reviewCount: 67,
    skills: ['LANDSCAPING', 'BOTANY'],
    hourlyRate: 28,
    verified: true,
    availableToday: true,
  },
  {
    id: '10',
    firstName: 'Sophie',
    lastName: 'Dubois',
    profileImage: 'https://ui-avatars.com/api/?name=Sophie+Dubois&background=random',
    title: 'French Language Tutor',
    category: 'Tutoring',
    rating: 4.9,
    reviewCount: 12,
    skills: ['FRENCH', 'LITERATURE'],
    hourlyRate: 30,
    verified: false,
    availableToday: false,
  },
  {
    id: '11',
    firstName: 'Michael',
    lastName: 'Brown',
    profileImage: 'https://ui-avatars.com/api/?name=Michael+Brown&background=random',
    title: 'Elderly Care Specialist',
    category: 'Elderly Care',
    rating: 5.0,
    reviewCount: 150,
    skills: ['PATIENT CARE', 'FIRST AID'],
    hourlyRate: 26,
    verified: true,
    availableToday: true,
  },
  {
    id: '12',
    firstName: 'Linda',
    lastName: 'Wei',
    profileImage: 'https://ui-avatars.com/api/?name=Linda+Wei&background=random',
    title: 'Piano Instructor',
    category: 'Music Lessons',
    rating: 4.8,
    reviewCount: 40,
    skills: ['MUSIC THEORY', 'PIANO'],
    hourlyRate: 55,
    verified: true,
    availableToday: false,
  },
  {
    id: '13',
    firstName: 'Robert',
    lastName: 'Fox',
    profileImage: 'https://ui-avatars.com/api/?name=Robert+Fox&background=random',
    title: 'Home Maintenance',
    category: 'Home Maintenance',
    rating: 4.4,
    reviewCount: 22,
    skills: ['PLUMBING', 'ELECTRICAL'],
    hourlyRate: 35,
    verified: false,
    availableToday: true,
  },
  {
    id: '14',
    firstName: 'Layla',
    lastName: 'Moussa',
    profileImage: 'https://ui-avatars.com/api/?name=Layla+Moussa&background=random',
    title: 'Personal Stylist',
    category: 'Personal Styling',
    rating: 4.7,
    reviewCount: 56,
    skills: ['FASHION', 'WARDROBE EDIT'],
    hourlyRate: 60,
    verified: true,
    availableToday: true,
  },
  {
    id: '15',
    firstName: 'Thomas',
    lastName: 'Müller',
    profileImage: 'https://ui-avatars.com/api/?name=Thomas+Muller&background=random',
    title: 'Dog Walker',
    category: 'Pet Care',
    rating: 4.9,
    reviewCount: 89,
    skills: ['ANIMAL CARE', 'TRAINING'],
    hourlyRate: 18,
    verified: true,
    availableToday: false,
  },
  {
    id: '16',
    firstName: 'Priya',
    lastName: 'Patel',
    profileImage: 'https://ui-avatars.com/api/?name=Priya+Patel&background=random',
    title: 'Yoga Instructor',
    category: 'Yoga & Fitness',
    rating: 4.8,
    reviewCount: 110,
    skills: ['VINYASA', 'MEDITATION'],
    hourlyRate: 45,
    verified: true,
    availableToday: true,
  },
  {
    id: '17',
    firstName: 'Gustavo',
    lastName: 'Silva',
    profileImage: 'https://ui-avatars.com/api/?name=Gustavo+Silva&background=random',
    title: 'Pool Technician',
    category: 'Pool Maintenance',
    rating: 4.6,
    reviewCount: 34,
    skills: ['POOL MAINTENANCE', 'CHEMISTRY'],
    hourlyRate: 25,
    verified: true,
    availableToday: true,
  },
  {
    id: '18',
    firstName: 'Anna',
    lastName: 'Kowalski',
    profileImage: 'https://ui-avatars.com/api/?name=Anna+Kowalski&background=random',
    title: 'Interior Decorator',
    category: 'Interior Design',
    rating: 4.7,
    reviewCount: 19,
    skills: ['DESIGN', 'COLOR THEORY'],
    hourlyRate: 50,
    verified: false,
    availableToday: false,
  },
  {
    id: '19',
    firstName: 'Omar',
    lastName: 'Farooq',
    profileImage: 'https://ui-avatars.com/api/?name=Omar+Farooq&background=random',
    title: 'IT Support',
    category: 'IT Support',
    rating: 4.9,
    reviewCount: 200,
    skills: ['NETWORKING', 'HARDWARE REPAIR'],
    hourlyRate: 40,
    verified: true,
    availableToday: true,
  },
  {
    id: '20',
    firstName: 'Grace',
    lastName: "O'Malley",
    profileImage: 'https://ui-avatars.com/api/?name=Grace+OMalley&background=random',
    title: 'Pet Sitter',
    category: 'Pet Care',
    rating: 4.8,
    reviewCount: 44,
    skills: ['CAT CARE', 'DOG CARE'],
    hourlyRate: 15,
    verified: true,
    availableToday: true,
  },
  {
    id: '21',
    firstName: 'Chen',
    lastName: 'Liu',
    profileImage: 'https://ui-avatars.com/api/?name=Chen+Liu&background=random',
    title: 'Violin Teacher',
    category: 'Music Lessons',
    rating: 5.0,
    reviewCount: 25,
    skills: ['CLASSICAL MUSIC', 'THEORY'],
    hourlyRate: 65,
    verified: true,
    availableToday: false,
  },
  {
    id: '22',
    firstName: 'Jessica',
    lastName: 'Alba',
    profileImage: 'https://ui-avatars.com/api/?name=Jessica+Alba&background=random',
    title: 'Makeup Artist',
    category: 'Personal Styling',
    rating: 4.5,
    reviewCount: 78,
    skills: ['BRIDAL', 'SPECIAL FX'],
    hourlyRate: 55,
    verified: true,
    availableToday: true,
  },
  {
    id: '23',
    firstName: 'William',
    lastName: 'Turner',
    profileImage: 'https://ui-avatars.com/api/?name=William+Turner&background=random',
    title: 'Carpenter',
    category: 'Home Maintenance',
    rating: 4.7,
    reviewCount: 92,
    skills: ['WOODWORKING', 'REPAIRS'],
    hourlyRate: 38,
    verified: true,
    availableToday: true,
  },
  {
    id: '24',
    firstName: 'Fatima',
    lastName: 'Nour',
    profileImage: 'https://ui-avatars.com/api/?name=Fatima+Nour&background=random',
    title: 'Arabic Calligrapher',
    category: 'Translation Services',
    rating: 4.9,
    reviewCount: 14,
    skills: ['ART', 'DESIGN'],
    hourlyRate: 40,
    verified: false,
    availableToday: false,
  },
  {
    id: '25',
    firstName: 'Lucas',
    lastName: 'Moreau',
    profileImage: 'https://ui-avatars.com/api/?name=Lucas+Moreau&background=random',
    title: 'Pastry Chef',
    category: 'Butler Services',
    rating: 4.8,
    reviewCount: 130,
    skills: ['BAKING', 'DESSERTS'],
    hourlyRate: 32,
    verified: true,
    availableToday: true,
  },
  {
    id: '26',
    firstName: 'Elena',
    lastName: 'Popov',
    profileImage: 'https://ui-avatars.com/api/?name=Elena+Popov&background=random',
    title: 'Swim Instructor',
    category: 'Personal Training',
    rating: 4.6,
    reviewCount: 28,
    skills: ['SWIMMING', 'WATER SAFETY'],
    hourlyRate: 25,
    verified: true,
    availableToday: false,
  },
  {
    id: '27',
    firstName: 'Samuel',
    lastName: 'Jackson',
    profileImage: 'https://ui-avatars.com/api/?name=Samuel+Jackson&background=random',
    title: 'Security Guard',
    category: 'Butler Services',
    rating: 4.5,
    reviewCount: 60,
    skills: ['SURVEILLANCE', 'PROTECTION'],
    hourlyRate: 20,
    verified: true,
    availableToday: true,
  },
  {
    id: '28',
    firstName: 'Hana',
    lastName: 'Kimura',
    profileImage: 'https://ui-avatars.com/api/?name=Hana+Kimura&background=random',
    title: 'Translator',
    category: 'Translation Services',
    rating: 4.9,
    reviewCount: 88,
    skills: ['JAPANESE', 'ENGLISH'],
    hourlyRate: 45,
    verified: true,
    availableToday: true,
  },
  {
    id: '29',
    firstName: 'Oliver',
    lastName: 'Smith',
    profileImage: 'https://ui-avatars.com/api/?name=Oliver+Smith&background=random',
    title: 'Bartender',
    category: 'Bartending',
    rating: 4.7,
    reviewCount: 112,
    skills: ['MIXOLOGY', 'CUSTOMER SERVICE'],
    hourlyRate: 28,
    verified: true,
    availableToday: false,
  },
  {
    id: '30',
    firstName: 'Zoe',
    lastName: 'Brooks',
    profileImage: 'https://ui-avatars.com/api/?name=Zoe+Brooks&background=random',
    title: 'Photographer',
    category: 'Photography',
    rating: 4.8,
    reviewCount: 145,
    skills: ['PORTRAITS', 'EDITING'],
    hourlyRate: 75,
    verified: true,
    availableToday: true,
  },

  {
    id: '1',
    firstName: 'Karim',
    lastName: 'Hassan',
    profileImage: 'https://ui-avatars.com/api/?name=Karim+Hassan&background=0D8ABC&color=fff',
    title: 'Certified Private Butler',
    category: 'Butler Services',
    rating: 4.9,
    reviewCount: 120,
    skills: ['EVENT MANAGEMENT', 'FRENCH SPEAKING'],
    hourlyRate: 25,
    verified: true,
    availableToday: true,
  },
  {
    id: '2',
    firstName: 'Sarah',
    lastName: 'Johnson',
    profileImage: 'https://ui-avatars.com/api/?name=Sarah+Johnson&background=random',
    title: 'Professional Chef',
    category: 'Butler Services',
    rating: 4.8,
    reviewCount: 95,
    skills: ['FINE DINING', 'ITALIAN CUISINE'],
    hourlyRate: 35,
    verified: true,
    availableToday: false,
  },
  {
    id: '3',
    firstName: 'Maria',
    lastName: 'Rodriguez',
    profileImage: 'https://ui-avatars.com/api/?name=Maria+Rodriguez&background=random',
    title: 'Senior Housekeeper',
    category: 'House Cleaning',
    rating: 4.7,
    reviewCount: 210,
    skills: ['DEEP CLEANING', 'ORGANIZATION'],
    hourlyRate: 20,
    verified: true,
    availableToday: true,
  },
  {
    id: '4',
    firstName: 'James',
    lastName: 'Wilson',
    profileImage: 'https://ui-avatars.com/api/?name=James+Wilson&background=random',
    title: 'Executive Chauffeur',
    category: 'Chauffeur & Drivers',
    rating: 5.0,
    reviewCount: 45,
    skills: ['DEFENSIVE DRIVING', 'SECURITY'],
    hourlyRate: 30,
    verified: true,
    availableToday: true,
  },
  {
    id: '5',
    firstName: 'Yuki',
    lastName: 'Tanaka',
    profileImage: 'https://ui-avatars.com/api/?name=Yuki+Tanaka&background=random',
    title: 'Math Tutor',
    category: 'Tutoring',
    rating: 4.9,
    reviewCount: 88,
    skills: ['CALCULUS', 'PHYSICS'],
    hourlyRate: 40,
    verified: true,
    availableToday: false,
  },
  {
    id: '6',
    firstName: 'Emily',
    lastName: 'Parker',
    profileImage: 'https://ui-avatars.com/api/?name=Emily+Parker&background=random',
    title: 'Nanny & Childcare',
    category: 'Childcare & Nanny',
    rating: 4.6,
    reviewCount: 15,
    skills: ['CPR CERTIFIED', 'EARLY EDUCATION'],
    hourlyRate: 22,
    verified: false,
    availableToday: true,
  },
  {
    id: '7',
    firstName: 'Ahmed',
    lastName: 'Al-Fayed',
    profileImage: 'https://ui-avatars.com/api/?name=Ahmed+Al-Fayed&background=random',
    title: 'Personal Trainer',
    category: 'Personal Training',
    rating: 4.8,
    reviewCount: 102,
    skills: ['WEIGHT LOSS', 'NUTRITION'],
    hourlyRate: 50,
    verified: true,
    availableToday: true,
  },
  {
    id: '8',
    firstName: 'Isabella',
    lastName: 'Rossi',
    profileImage: 'https://ui-avatars.com/api/?name=Isabella+Rossi&background=random',
    title: 'Event Planner',
    category: 'Event Planning',
    rating: 4.5,
    reviewCount: 30,
    skills: ['WEDDINGS', 'CATERING LOGISTICS'],
    hourlyRate: 45,
    verified: true,
    availableToday: false,
  },
  {
    id: '9',
    firstName: 'David',
    lastName: 'Kim',
    profileImage: 'https://ui-avatars.com/api/?name=David+Kim&background=random',
    title: 'Landscape Gardener',
    category: 'Landscaping & Gardening',
    rating: 4.7,
    reviewCount: 67,
    skills: ['LANDSCAPING', 'BOTANY'],
    hourlyRate: 28,
    verified: true,
    availableToday: true,
  },
  {
    id: '10',
    firstName: 'Sophie',
    lastName: 'Dubois',
    profileImage: 'https://ui-avatars.com/api/?name=Sophie+Dubois&background=random',
    title: 'French Language Tutor',
    category: 'Tutoring',
    rating: 4.9,
    reviewCount: 12,
    skills: ['FRENCH', 'LITERATURE'],
    hourlyRate: 30,
    verified: false,
    availableToday: false,
  },
  {
    id: '11',
    firstName: 'Michael',
    lastName: 'Brown',
    profileImage: 'https://ui-avatars.com/api/?name=Michael+Brown&background=random',
    title: 'Elderly Care Specialist',
    category: 'Elderly Care',
    rating: 5.0,
    reviewCount: 150,
    skills: ['PATIENT CARE', 'FIRST AID'],
    hourlyRate: 26,
    verified: true,
    availableToday: true,
  },
  {
    id: '12',
    firstName: 'Linda',
    lastName: 'Wei',
    profileImage: 'https://ui-avatars.com/api/?name=Linda+Wei&background=random',
    title: 'Piano Instructor',
    category: 'Music Lessons',
    rating: 4.8,
    reviewCount: 40,
    skills: ['MUSIC THEORY', 'PIANO'],
    hourlyRate: 55,
    verified: true,
    availableToday: false,
  },
  {
    id: '13',
    firstName: 'Robert',
    lastName: 'Fox',
    profileImage: 'https://ui-avatars.com/api/?name=Robert+Fox&background=random',
    title: 'Home Maintenance',
    category: 'Home Maintenance',
    rating: 4.4,
    reviewCount: 22,
    skills: ['PLUMBING', 'ELECTRICAL'],
    hourlyRate: 35,
    verified: false,
    availableToday: true,
  },
  {
    id: '14',
    firstName: 'Layla',
    lastName: 'Moussa',
    profileImage: 'https://ui-avatars.com/api/?name=Layla+Moussa&background=random',
    title: 'Personal Stylist',
    category: 'Personal Styling',
    rating: 4.7,
    reviewCount: 56,
    skills: ['FASHION', 'WARDROBE EDIT'],
    hourlyRate: 60,
    verified: true,
    availableToday: true,
  },
  {
    id: '15',
    firstName: 'Thomas',
    lastName: 'Müller',
    profileImage: 'https://ui-avatars.com/api/?name=Thomas+Muller&background=random',
    title: 'Dog Walker',
    category: 'Pet Care',
    rating: 4.9,
    reviewCount: 89,
    skills: ['ANIMAL CARE', 'TRAINING'],
    hourlyRate: 18,
    verified: true,
    availableToday: false,
  },
  {
    id: '16',
    firstName: 'Priya',
    lastName: 'Patel',
    profileImage: 'https://ui-avatars.com/api/?name=Priya+Patel&background=random',
    title: 'Yoga Instructor',
    category: 'Yoga & Fitness',
    rating: 4.8,
    reviewCount: 110,
    skills: ['VINYASA', 'MEDITATION'],
    hourlyRate: 45,
    verified: true,
    availableToday: true,
  },
  {
    id: '17',
    firstName: 'Gustavo',
    lastName: 'Silva',
    profileImage: 'https://ui-avatars.com/api/?name=Gustavo+Silva&background=random',
    title: 'Pool Technician',
    category: 'Pool Maintenance',
    rating: 4.6,
    reviewCount: 34,
    skills: ['POOL MAINTENANCE', 'CHEMISTRY'],
    hourlyRate: 25,
    verified: true,
    availableToday: true,
  },
  {
    id: '18',
    firstName: 'Anna',
    lastName: 'Kowalski',
    profileImage: 'https://ui-avatars.com/api/?name=Anna+Kowalski&background=random',
    title: 'Interior Decorator',
    category: 'Interior Design',
    rating: 4.7,
    reviewCount: 19,
    skills: ['DESIGN', 'COLOR THEORY'],
    hourlyRate: 50,
    verified: false,
    availableToday: false,
  },
  {
    id: '19',
    firstName: 'Omar',
    lastName: 'Farooq',
    profileImage: 'https://ui-avatars.com/api/?name=Omar+Farooq&background=random',
    title: 'IT Support',
    category: 'IT Support',
    rating: 4.9,
    reviewCount: 200,
    skills: ['NETWORKING', 'HARDWARE REPAIR'],
    hourlyRate: 40,
    verified: true,
    availableToday: true,
  },
  {
    id: '20',
    firstName: 'Grace',
    lastName: "O'Malley",
    profileImage: 'https://ui-avatars.com/api/?name=Grace+OMalley&background=random',
    title: 'Pet Sitter',
    category: 'Pet Care',
    rating: 4.8,
    reviewCount: 44,
    skills: ['CAT CARE', 'DOG CARE'],
    hourlyRate: 15,
    verified: true,
    availableToday: true,
  },
  {
    id: '21',
    firstName: 'Chen',
    lastName: 'Liu',
    profileImage: 'https://ui-avatars.com/api/?name=Chen+Liu&background=random',
    title: 'Violin Teacher',
    category: 'Music Lessons',
    rating: 5.0,
    reviewCount: 25,
    skills: ['CLASSICAL MUSIC', 'THEORY'],
    hourlyRate: 65,
    verified: true,
    availableToday: false,
  },
  {
    id: '22',
    firstName: 'Jessica',
    lastName: 'Alba',
    profileImage: 'https://ui-avatars.com/api/?name=Jessica+Alba&background=random',
    title: 'Makeup Artist',
    category: 'Personal Styling',
    rating: 4.5,
    reviewCount: 78,
    skills: ['BRIDAL', 'SPECIAL FX'],
    hourlyRate: 55,
    verified: true,
    availableToday: true,
  },
  {
    id: '23',
    firstName: 'William',
    lastName: 'Turner',
    profileImage: 'https://ui-avatars.com/api/?name=William+Turner&background=random',
    title: 'Carpenter',
    category: 'Home Maintenance',
    rating: 4.7,
    reviewCount: 92,
    skills: ['WOODWORKING', 'REPAIRS'],
    hourlyRate: 38,
    verified: true,
    availableToday: true,
  },
  {
    id: '24',
    firstName: 'Fatima',
    lastName: 'Nour',
    profileImage: 'https://ui-avatars.com/api/?name=Fatima+Nour&background=random',
    title: 'Arabic Calligrapher',
    category: 'Translation Services',
    rating: 4.9,
    reviewCount: 14,
    skills: ['ART', 'DESIGN'],
    hourlyRate: 40,
    verified: false,
    availableToday: false,
  },
  {
    id: '25',
    firstName: 'Lucas',
    lastName: 'Moreau',
    profileImage: 'https://ui-avatars.com/api/?name=Lucas+Moreau&background=random',
    title: 'Pastry Chef',
    category: 'Butler Services',
    rating: 4.8,
    reviewCount: 130,
    skills: ['BAKING', 'DESSERTS'],
    hourlyRate: 32,
    verified: true,
    availableToday: true,
  },
  {
    id: '26',
    firstName: 'Elena',
    lastName: 'Popov',
    profileImage: 'https://ui-avatars.com/api/?name=Elena+Popov&background=random',
    title: 'Swim Instructor',
    category: 'Personal Training',
    rating: 4.6,
    reviewCount: 28,
    skills: ['SWIMMING', 'WATER SAFETY'],
    hourlyRate: 25,
    verified: true,
    availableToday: false,
  },
  {
    id: '27',
    firstName: 'Samuel',
    lastName: 'Jackson',
    profileImage: 'https://ui-avatars.com/api/?name=Samuel+Jackson&background=random',
    title: 'Security Guard',
    category: 'Butler Services',
    rating: 4.5,
    reviewCount: 60,
    skills: ['SURVEILLANCE', 'PROTECTION'],
    hourlyRate: 20,
    verified: true,
    availableToday: true,
  },
  {
    id: '28',
    firstName: 'Hana',
    lastName: 'Kimura',
    profileImage: 'https://ui-avatars.com/api/?name=Hana+Kimura&background=random',
    title: 'Translator',
    category: 'Translation Services',
    rating: 4.9,
    reviewCount: 88,
    skills: ['JAPANESE', 'ENGLISH'],
    hourlyRate: 45,
    verified: true,
    availableToday: true,
  },
  {
    id: '29',
    firstName: 'Oliver',
    lastName: 'Smith',
    profileImage: 'https://ui-avatars.com/api/?name=Oliver+Smith&background=random',
    title: 'Bartender',
    category: 'Bartending',
    rating: 4.7,
    reviewCount: 112,
    skills: ['MIXOLOGY', 'CUSTOMER SERVICE'],
    hourlyRate: 28,
    verified: true,
    availableToday: false,
  },
  {
    id: '30',
    firstName: 'Zoe',
    lastName: 'Brooks',
    profileImage: 'https://ui-avatars.com/api/?name=Zoe+Brooks&background=random',
    title: 'Photographer',
    category: 'Photography',
    rating: 4.8,
    reviewCount: 145,
    skills: ['PORTRAITS', 'EDITING'],
    hourlyRate: 75,
    verified: true,
    availableToday: true,
  },

  {
    id: '2',
    firstName: 'Sarah',
    lastName: 'Johnson',
    profileImage: 'https://ui-avatars.com/api/?name=Sarah+Johnson&background=random',
    title: 'Professional Chef',
    category: 'Butler Services',
    rating: 4.8,
    reviewCount: 95,
    skills: ['FINE DINING', 'ITALIAN CUISINE'],
    hourlyRate: 35,
    verified: true,
    availableToday: false,
  },
  {
    id: '3',
    firstName: 'Maria',
    lastName: 'Rodriguez',
    profileImage: 'https://ui-avatars.com/api/?name=Maria+Rodriguez&background=random',
    title: 'Senior Housekeeper',
    category: 'House Cleaning',
    rating: 4.7,
    reviewCount: 210,
    skills: ['DEEP CLEANING', 'ORGANIZATION'],
    hourlyRate: 20,
    verified: true,
    availableToday: true,
  },
  {
    id: '4',
    firstName: 'James',
    lastName: 'Wilson',
    profileImage: 'https://ui-avatars.com/api/?name=James+Wilson&background=random',
    title: 'Executive Chauffeur',
    category: 'Chauffeur & Drivers',
    rating: 5.0,
    reviewCount: 45,
    skills: ['DEFENSIVE DRIVING', 'SECURITY'],
    hourlyRate: 30,
    verified: true,
    availableToday: true,
  },
  {
    id: '5',
    firstName: 'Yuki',
    lastName: 'Tanaka',
    profileImage: 'https://ui-avatars.com/api/?name=Yuki+Tanaka&background=random',
    title: 'Math Tutor',
    category: 'Tutoring',
    rating: 4.9,
    reviewCount: 88,
    skills: ['CALCULUS', 'PHYSICS'],
    hourlyRate: 40,
    verified: true,
    availableToday: false,
  },
  {
    id: '6',
    firstName: 'Emily',
    lastName: 'Parker',
    profileImage: 'https://ui-avatars.com/api/?name=Emily+Parker&background=random',
    title: 'Nanny & Childcare',
    category: 'Childcare & Nanny',
    rating: 4.6,
    reviewCount: 15,
    skills: ['CPR CERTIFIED', 'EARLY EDUCATION'],
    hourlyRate: 22,
    verified: false,
    availableToday: true,
  },
  {
    id: '7',
    firstName: 'Ahmed',
    lastName: 'Al-Fayed',
    profileImage: 'https://ui-avatars.com/api/?name=Ahmed+Al-Fayed&background=random',
    title: 'Personal Trainer',
    category: 'Personal Training',
    rating: 4.8,
    reviewCount: 102,
    skills: ['WEIGHT LOSS', 'NUTRITION'],
    hourlyRate: 50,
    verified: true,
    availableToday: true,
  },
  {
    id: '8',
    firstName: 'Isabella',
    lastName: 'Rossi',
    profileImage: 'https://ui-avatars.com/api/?name=Isabella+Rossi&background=random',
    title: 'Event Planner',
    category: 'Event Planning',
    rating: 4.5,
    reviewCount: 30,
    skills: ['WEDDINGS', 'CATERING LOGISTICS'],
    hourlyRate: 45,
    verified: true,
    availableToday: false,
  },
  {
    id: '9',
    firstName: 'David',
    lastName: 'Kim',
    profileImage: 'https://ui-avatars.com/api/?name=David+Kim&background=random',
    title: 'Landscape Gardener',
    category: 'Landscaping & Gardening',
    rating: 4.7,
    reviewCount: 67,
    skills: ['LANDSCAPING', 'BOTANY'],
    hourlyRate: 28,
    verified: true,
    availableToday: true,
  },
  {
    id: '10',
    firstName: 'Sophie',
    lastName: 'Dubois',
    profileImage: 'https://ui-avatars.com/api/?name=Sophie+Dubois&background=random',
    title: 'French Language Tutor',
    category: 'Tutoring',
    rating: 4.9,
    reviewCount: 12,
    skills: ['FRENCH', 'LITERATURE'],
    hourlyRate: 30,
    verified: false,
    availableToday: false,
  },
  {
    id: '11',
    firstName: 'Michael',
    lastName: 'Brown',
    profileImage: 'https://ui-avatars.com/api/?name=Michael+Brown&background=random',
    title: 'Elderly Care Specialist',
    category: 'Elderly Care',
    rating: 5.0,
    reviewCount: 150,
    skills: ['PATIENT CARE', 'FIRST AID'],
    hourlyRate: 26,
    verified: true,
    availableToday: true,
  },
  {
    id: '12',
    firstName: 'Linda',
    lastName: 'Wei',
    profileImage: 'https://ui-avatars.com/api/?name=Linda+Wei&background=random',
    title: 'Piano Instructor',
    category: 'Music Lessons',
    rating: 4.8,
    reviewCount: 40,
    skills: ['MUSIC THEORY', 'PIANO'],
    hourlyRate: 55,
    verified: true,
    availableToday: false,
  },
  {
    id: '13',
    firstName: 'Robert',
    lastName: 'Fox',
    profileImage: 'https://ui-avatars.com/api/?name=Robert+Fox&background=random',
    title: 'Home Maintenance',
    category: 'Home Maintenance',
    rating: 4.4,
    reviewCount: 22,
    skills: ['PLUMBING', 'ELECTRICAL'],
    hourlyRate: 35,
    verified: false,
    availableToday: true,
  },
  {
    id: '14',
    firstName: 'Layla',
    lastName: 'Moussa',
    profileImage: 'https://ui-avatars.com/api/?name=Layla+Moussa&background=random',
    title: 'Personal Stylist',
    category: 'Personal Styling',
    rating: 4.7,
    reviewCount: 56,
    skills: ['FASHION', 'WARDROBE EDIT'],
    hourlyRate: 60,
    verified: true,
    availableToday: true,
  },
  {
    id: '15',
    firstName: 'Thomas',
    lastName: 'Müller',
    profileImage: 'https://ui-avatars.com/api/?name=Thomas+Muller&background=random',
    title: 'Dog Walker',
    category: 'Pet Care',
    rating: 4.9,
    reviewCount: 89,
    skills: ['ANIMAL CARE', 'TRAINING'],
    hourlyRate: 18,
    verified: true,
    availableToday: false,
  },
  {
    id: '16',
    firstName: 'Priya',
    lastName: 'Patel',
    profileImage: 'https://ui-avatars.com/api/?name=Priya+Patel&background=random',
    title: 'Yoga Instructor',
    category: 'Yoga & Fitness',
    rating: 4.8,
    reviewCount: 110,
    skills: ['VINYASA', 'MEDITATION'],
    hourlyRate: 45,
    verified: true,
    availableToday: true,
  },
  {
    id: '17',
    firstName: 'Gustavo',
    lastName: 'Silva',
    profileImage: 'https://ui-avatars.com/api/?name=Gustavo+Silva&background=random',
    title: 'Pool Technician',
    category: 'Pool Maintenance',
    rating: 4.6,
    reviewCount: 34,
    skills: ['POOL MAINTENANCE', 'CHEMISTRY'],
    hourlyRate: 25,
    verified: true,
    availableToday: true,
  },
  {
    id: '18',
    firstName: 'Anna',
    lastName: 'Kowalski',
    profileImage: 'https://ui-avatars.com/api/?name=Anna+Kowalski&background=random',
    title: 'Interior Decorator',
    category: 'Interior Design',
    rating: 4.7,
    reviewCount: 19,
    skills: ['DESIGN', 'COLOR THEORY'],
    hourlyRate: 50,
    verified: false,
    availableToday: false,
  },
  {
    id: '19',
    firstName: 'Omar',
    lastName: 'Farooq',
    profileImage: 'https://ui-avatars.com/api/?name=Omar+Farooq&background=random',
    title: 'IT Support',
    category: 'IT Support',
    rating: 4.9,
    reviewCount: 200,
    skills: ['NETWORKING', 'HARDWARE REPAIR'],
    hourlyRate: 40,
    verified: true,
    availableToday: true,
  },
  {
    id: '20',
    firstName: 'Grace',
    lastName: "O'Malley",
    profileImage: 'https://ui-avatars.com/api/?name=Grace+OMalley&background=random',
    title: 'Pet Sitter',
    category: 'Pet Care',
    rating: 4.8,
    reviewCount: 44,
    skills: ['CAT CARE', 'DOG CARE'],
    hourlyRate: 15,
    verified: true,
    availableToday: true,
  },
  {
    id: '21',
    firstName: 'Chen',
    lastName: 'Liu',
    profileImage: 'https://ui-avatars.com/api/?name=Chen+Liu&background=random',
    title: 'Violin Teacher',
    category: 'Music Lessons',
    rating: 5.0,
    reviewCount: 25,
    skills: ['CLASSICAL MUSIC', 'THEORY'],
    hourlyRate: 65,
    verified: true,
    availableToday: false,
  },
  {
    id: '22',
    firstName: 'Jessica',
    lastName: 'Alba',
    profileImage: 'https://ui-avatars.com/api/?name=Jessica+Alba&background=random',
    title: 'Makeup Artist',
    category: 'Personal Styling',
    rating: 4.5,
    reviewCount: 78,
    skills: ['BRIDAL', 'SPECIAL FX'],
    hourlyRate: 55,
    verified: true,
    availableToday: true,
  },
  {
    id: '23',
    firstName: 'William',
    lastName: 'Turner',
    profileImage: 'https://ui-avatars.com/api/?name=William+Turner&background=random',
    title: 'Carpenter',
    category: 'Home Maintenance',
    rating: 4.7,
    reviewCount: 92,
    skills: ['WOODWORKING', 'REPAIRS'],
    hourlyRate: 38,
    verified: true,
    availableToday: true,
  },
  {
    id: '24',
    firstName: 'Fatima',
    lastName: 'Nour',
    profileImage: 'https://ui-avatars.com/api/?name=Fatima+Nour&background=random',
    title: 'Arabic Calligrapher',
    category: 'Translation Services',
    rating: 4.9,
    reviewCount: 14,
    skills: ['ART', 'DESIGN'],
    hourlyRate: 40,
    verified: false,
    availableToday: false,
  },
  {
    id: '25',
    firstName: 'Lucas',
    lastName: 'Moreau',
    profileImage: 'https://ui-avatars.com/api/?name=Lucas+Moreau&background=random',
    title: 'Pastry Chef',
    category: 'Butler Services',
    rating: 4.8,
    reviewCount: 130,
    skills: ['BAKING', 'DESSERTS'],
    hourlyRate: 32,
    verified: true,
    availableToday: true,
  },
  {
    id: '26',
    firstName: 'Elena',
    lastName: 'Popov',
    profileImage: 'https://ui-avatars.com/api/?name=Elena+Popov&background=random',
    title: 'Swim Instructor',
    category: 'Personal Training',
    rating: 4.6,
    reviewCount: 28,
    skills: ['SWIMMING', 'WATER SAFETY'],
    hourlyRate: 25,
    verified: true,
    availableToday: false,
  },
  {
    id: '27',
    firstName: 'Samuel',
    lastName: 'Jackson',
    profileImage: 'https://ui-avatars.com/api/?name=Samuel+Jackson&background=random',
    title: 'Security Guard',
    category: 'Butler Services',
    rating: 4.5,
    reviewCount: 60,
    skills: ['SURVEILLANCE', 'PROTECTION'],
    hourlyRate: 20,
    verified: true,
    availableToday: true,
  },
  {
    id: '28',
    firstName: 'Hana',
    lastName: 'Kimura',
    profileImage: 'https://ui-avatars.com/api/?name=Hana+Kimura&background=random',
    title: 'Translator',
    category: 'Translation Services',
    rating: 4.9,
    reviewCount: 88,
    skills: ['JAPANESE', 'ENGLISH'],
    hourlyRate: 45,
    verified: true,
    availableToday: true,
  },
  {
    id: '29',
    firstName: 'Oliver',
    lastName: 'Smith',
    profileImage: 'https://ui-avatars.com/api/?name=Oliver+Smith&background=random',
    title: 'Bartender',
    category: 'Bartending',
    rating: 4.7,
    reviewCount: 112,
    skills: ['MIXOLOGY', 'CUSTOMER SERVICE'],
    hourlyRate: 28,
    verified: true,
    availableToday: false,
  },
  {
    id: '30',
    firstName: 'Zoe',
    lastName: 'Brooks',
    profileImage: 'https://ui-avatars.com/api/?name=Zoe+Brooks&background=random',
    title: 'Photographer',
    category: 'Photography',
    rating: 4.8,
    reviewCount: 145,
    skills: ['PORTRAITS', 'EDITING'],
    hourlyRate: 75,
    verified: true,
    availableToday: true,
  },
];
